version: '2'
services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${postgres_db}
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    tty: true
    network_mode: host
    stdin_open: true
    oom_kill_disable: true
    command: -p ${server_port} -c max_connections=${max_connections} -c shared_buffers=${shared_buffers} -c work_mem=${work_mem} -c effective_cache_size=${effective_cache_size} ${server_configuration}
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_label}
    volumes:
      - $volumen_name:/var/lib/postgresql/data/pgdata
volumes:
  $volumen_name:
    driver: local
    # por seguridad para no perder si alguienb borra el stack, se debe crear con
    # rancher volume create --driver local pgdata
    external: true
