version: '2'
services:
    odoo:
        image: adhoc/odoo-ar-e:$strImageTag
        labels:
            io.rancher.container.pull_image: always
            # io.rancher.sidekicks: odoo-sessions
            # para cuando traefik de rancer soporte multiples backends
            # traefik.enable: true
            # traefik.frontend.rule: Host:$strTraefikDomains
            # traefik.port: 8069
            # traefik.frontend.rule: Host:$strTraefikDomains
            # traefik.longpolling.port: 8072
            # traefik.longpolling.frontend.rule: Host:$strTraefikDomains;PathPrefix:/longpolling/
            # traefik.websiteinfo.auth.basic: "$strPgUser:$strAdminPassword"
            # traefik.websiteinfo.frontend.rule: Host:$strTraefikDomains;PathPrefix:/website/info
            # traefik.dbmanager.auth.basic: "$strPgUser:$strAdminPassword"
            # traefik.dbmanager.frontend.rule: Host:$strTraefikDomains;PathPrefix:/web/database/
        volumes:
            - odoo_data_filestore:/opt/odoo/data/filestore/
            - odoo_data_session:/opt/odoo/data/sessions/
        environment:
            # database parameters
            - PGUSER=$strPgUser
            - PGPASSWORD=$strPgPassword
            - PGHOST=$strPgHost
            # TODO, este podria volver a ser un booleano y tmb podriamos
            # re simplificar el entry point, ahora modificamos a odoo para que
            # no cree bd si se manda el db_name, y estamos haciendo eso, mandar
            # db_name
            - FIXDBS=$strFixDbs
            - SMTP_SERVER=$strSmtpServer
            - SMTP_PORT=$intSmtPort
            - SMTP_SSL=$boolSmtpSsl
            - SMTP_USER=$strSmtpUser
            - SMTP_PASSWORD=$strSmtPassword
            - AEROO_DOCS_HOST= aeroo-docs.adhoc-aeroo-docs
            - DATABASE=$strDatabase
            - DBFILTER=$strDbFilter
            - SERVER_MODE=$strServerMode
            - DISABLE_SESSION_GC=$strDisableSessionGC
            - WORKERS=$intWorkers
            - ADMIN_PASSWORD=$strAdminPassword
            - MAIL_CATCHALL_DOMAIN=$strMailCatchallDomain
            - FIX_DB_WEB_DISABLED=True
            - PG_MAX_CONNECTIONS=$intPgMaxConnections
            - LIMIT_MEMORY_HARD=$intLimitMemoryHard
            - LIMIT_MEMORY_SOFT=$intLimitMemorySoft
            - ODOO_VERSION=$strImageTag
    odoo-lb:
        image: rancher/lb-service-haproxy
        labels:
            # io.rancher.container.agent.role: environmentAdmin,agent
            # io.rancher.container.agent_service.drain_provider: 'true'
            # io.rancher.container.create_agent: 'true'
            traefik.enable: true
            traefik.frontend.rule: Host:$strTraefikDomains
            traefik.port: 80
            traefik.backend.loadbalancer.stickiness: true
            traefik.backend.loadbalancer.method: drr
volumes:
  odoo_data_session:
    driver: rancher-nfs
    external: true
  odoo_data_filestore:
    driver: rancher-nfs
    external: true
