version: '2'
services:
    postfix:
        tty: true
        stdin_open: true
        ports:
            - 25:25/tcp
        labels:
            io.rancher.scheduler.global: 'true'
            io.rancher.scheduler.affinity:host_label: ${host_label}
            io.rancher.container.pull_image: always
            # al final solo lo usamos para entrada por lo cual el link
            # no esnecesario
            # used to be autolinked on odoo containers
            # odoo_service: True
        environment:
            # variables for receiving emails
            - CATCHALL_DOMAIN=$cCatchallDomain
            - DOMAIN_REGEX=$cDomainRegex
            - MAIL_ADMINS=$cMailAdmins
            - ODOO_PORT=$iOdooPort
            - ODOO_PROTOCOL=$eOdooProtocol
            # variables for sending emails (postfix rejections)
            # - cMyHostname=$cMyHostname
            - MYNETWORKS=$cMyNetworks
            - cRelayHostLine=$cRelayHostLine
            - cRelaySASLUser=$cRelaySASLUser
            - cRelaySASLPasswd=$cRelaySASLPasswd
        image: adhoc/odoo-postfix
