.catalog:
  name: "ADHOC Odoo Postfix"
  version: "1.0"
  description: "Postfix stack used to deliver mails to odoo stacks and also to send emails from stacks"
  minimum_rancher_version: v1.3.2
  questions:

    - variable: cMailAdmins
      label: "Mail Admins"
      description: "aa"
      # description: "Tuple of eMails where wrong deliveryies will be notified splitted by ',' and between ()"
      type: "string"
      required: true
      default: "('info@example.com',)"

    # Variables for sending emails
    - variable: cMyHostname
      label: "Postfix Hostname"
      description: "Postfix main.cf myhostname configuration parameter. Usually FQDN of host. E.g. acme.company.org."
      type: "string"
      required: true
      default: "mail.sistemasadhoc.com"

    - variable: cRelayHostLine
      label: "Optional Postfix Relay Host"
      description: "Postfix main.cf relayhost configuration parameter [host]:port format. E.g. [smtp.sendgrid.net]:2525"
      type: "string"
      required: false
      default: "[smtp.sendgrid.net]:2525"

    - variable: cRelaySASLUser
      label: "Optional Username for Relay Host"
      description: "Enter your optional relayhost SASL user name. If you enter a relay host this is required."
      type: "string"
      required: false
      default: ""

    - variable: cRelaySASLPasswd
      label: "Optional Passwd for Relay Host"
      description: "Enter your optional relayhost SASL password. If you enter a relay host this is required."
      type: "string"
      required: false
      default: ""
#
# Scaling and health checks per service as per docker-compose.yml
#
version: 2
services:
  postfix-dockprox:
    scale: 1
    health_check:
      port: 25
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
