.catalog:
  name: "Adhoc Traefik"
  version: "1.3.2"
  description: "(Experimental) Traefik load balancer."
  minimum_rancher_version: v1.3.2
  questions:

#
# Scaling and health checks per service as per docker-compose.yml
#
version: 2
services:
  traefik:
    retain_ip: true
    health_check:
      port: 8000
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET /dashboard/# HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000
