.catalog:
  name: "Adhoc Traefik"
  version: "v1.3.2-rancher1"
  description: "(Experimental) Traefik load balancer."
  minimum_rancher_version: v1.3.2
    - variable: "http_port"
        description: "Traefik http public port to listen."
        label: "Http port:"
        required: true
        default: 80
        type: "int"
    - variable: "https_port"
        description: "Traefik https public port to listen."
        label: "Https port:"
        required: true
        default: 443
        type: "int"
    - variable: "admin_port"
        description: "Traefik admin public port to listen."
        label: "Admin port:"
        required: true
        default: 8000 
        type: "int"
    - variable: "domain"
        description: "Can be overridden by setting the "traefik.domain" label on an service."
        label: "Default domain used:"
        required: true
        default: "rancher.localhost"
        type: "str"
  # Variables for receiving emails
    - variable: cCatchallDomain
      label: "Catchall Domain"
      description: "domain that is using as wildcar for the catchall, for eg 'nubeadhoc.com'. We use it to check if incoming email to addrees, has that domain or not."
      type: "string"
      required: false
      default: "nubeadhoc.com"

    - variable: cDomainRegex
      label: "Postfix Domain Regex"
      description: "Postfix domain regex for accepting mail based on SaaS Odoo hosting shared domain. E.g. domain2.com"
      type: "string"
      required: false
      # TODO ver como pasar este default o contruirlo
      # default: "/(.*)nubeadhoc\.com$/"

    - variable: cMailAdmins
      label: "Mail Admins"
      description: "List of eMails where wrong deliveryies will be notified splitted by ','"
      type: "string"
      required: true
      default: "info@example.com"

  # Variables for sending emails
    # - variable: cMyHostname
    #   label: "Postfix Hostname"
    #   description: "Postfix main.cf myhostname configuration parameter. Usually FQDN of host. E.g. acme.company.org."
    #   type: "string"
    #   required: true
    #   default: "mail.sistemasadhoc.com"

    - variable: cMyNetworks
      label: "Optional My Networks"
      description: ""
      type: "string"
      required: false
      default: "10.0.0.0/8"

    - variable: cRelayHostLine
      label: "Optional Postfix Relay Host"
      description: "Postfix main.cf relayhost configuration parameter [host]:port format. E.g. [smtp.sendgrid.net]:2525"
      type: "string"
      required: false
      default: "[smtp.sendgrid.net]:2525"

    - variable: cRelaySASLUser
      label: "Optional Username for Relay Host"
      description: "Enter your optional relayhost SASL user name. If you enter a relay host this is required."
      type: "string"
      required: false
      default: ""

    - variable: cRelaySASLPasswd
      label: "Optional Passwd for Relay Host"
      description: "Enter your optional relayhost SASL password. If you enter a relay host this is required."
      type: "string"
      required: false
      default: ""
#
# Scaling and health checks per service as per docker-compose.yml
#
version: 2
services:
  postfix-dockprox:
    scale: 1
    health_check:
      port: 25
      interval: 2000
      initializing_timeout: 60000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 2000
