version: '2'
services:
    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            # TODO check if we use subdirectory as recommended here for GCE
            # https://hub.docker.com/_/postgres/
            - db_data:/var/lib/postgresql/data
    odoo:
        image: adhoc/odoo-ar-e:${strOdooVersion}
        depends_on:
            - db
        labels:
            io.rancher.service.selector.link: odoo_service=True
            io.rancher.container.pull_image: always
        volumes:
            - odoo_data:/opt/odoo/data
        environment:
            # TODO remove or use
            # - WITHOUT_DEMO=$boolWithoutDemo
            # - VIRTUAL_PORT=8069,8072
            # TODO borrar o usar, al final fuimos por hacer la config con odoo ws porque la var de stack_name no funciona y ademas queremos configurar el freeze y otros
            # - MAIL_CATCHALL_DOMAIN={$stack_name}.juans.dev-adhoc.com
            - SMTP_SERVER=postfix
            - AEROO_DOCS_HOST=aeroo-docs
            - DATABASE=$strDatabase
            - SERVER_MODE=$strServerMode
            - WORKERS=$intWorkers
            - ADMIN_PASSWORD=$strAdminPassword
            - MAIL_CATCHALL_DOMAIN=$strMailCatchallDomain
    nginx:
        image: adhoc/odoo-nginx
        depends_on:
            - odoo
        labels:
            traefik.enable: stack
            traefik.domain: $strTraefikDomain
            traefik.port: 80
            traefik.alias.fqdn: $cOtherServerNames
            io.rancher.container.pull_image: always
        # volumes:
        #     - nginx_conf:/etc/nginx/nginx.conf:ro
volumes:
    odoo_data:
        driver: rancher-nfs
        external: false
    db_data:
        driver: rancher-nfs
        external: false
    nginx_conf:
        driver: rancher-nfs
        external: true
