version: '2'
services:
    traefik:
        ports:
            - ${admin_port}:8000/tcp
            - ${http_port}:${http_port}/tcp
            - ${https_port}:${https_port}/tcp
            # log_driver: ''
        command:
            - --web
            - --rancher
            - --rancher.domain=${domain}
            - --rancher.endpoint=${Endpoint}
            - --rancher.accesskey=${AccessKey}
            - --rancher.secretkey=${SecretKey}
            # parameter para loglevel?
            # - --logLevel=DEBUG
        labels:
            io.rancher.scheduler.global: 'true'
            # io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
            # io.rancher.sidekicks: traefik-conf
            #   {{- if eq .Values.acme_enable "true" -}}
            #     ,traefik-acme
            #   {{- end}}
            # io.rancher.container.hostname_override: container_name
        tty: true
        # log_opt: {}
        image: traefik:1.3.2
        # environment:
        volumes:
            - traefik:/data
            - sslcerts:/ssl
            # - /opt/traefik/acme
            # - db_data:/var/lib/postgresql/data/pgdata
volumes:
    traefik:
        driver: rancher-nfs
        external: false
    sslcerts:
        driver: rancher-nfs
        external: false
# volumes:
#   sslcerts:
#     driver: local
#   traefik:
#     driver: local
