version: '2'
services:
    traefik:
        tty: true
        # log_opt: {}
        image: traefik:1.3.2
        # environment:
        volumes:
            - traefik:/data
            - sslcerts:/ssl
            # - /opt/traefik/acme
            # - db_data:/var/lib/postgresql/data/pgdata
volumes:
    traefik:
        driver: rancher-nfs
        external: false
    sslcerts:
        driver: rancher-nfs
        external: false
# volumes:
#   sslcerts:
#     driver: local
#   traefik:
#     driver: local
