version: '2'
services:
    traefik:
        ports:
            - ${admin_port}:8080/tcp
            - ${http_port}:80/tcp
            - ${https_port}:443/tcp
            # log_driver: ''
        command:
            - --web
            - --rancher
            - --rancher.domain=${domain}
            - --rancher.endpoint=${Endpoint}
            - --rancher.accesskey=${AccessKey}
            - --rancher.secretkey=${SecretKey}
            # parameter para loglevel?
            # - --logLevel=DEBUG
        labels:
            io.rancher.scheduler.global: 'true'
        tty: true
        # log_opt: {}
        image: traefik:1.3.2
        # environment:
        volumes:
            - traefik:/data
            - sslcerts:/ssl
            # - /opt/traefik/acme
            # - db_data:/var/lib/postgresql/data/pgdata
volumes:
    traefik:
        driver: rancher-nfs
        external: false
    sslcerts:
        driver: rancher-nfs
        external: false
# volumes:
#   sslcerts:
#     driver: local
#   traefik:
#     driver: local
