version: '2'
services:
    traefik:
        ports:
            - ${admin_port}:8080/tcp
            - ${http_port}:80/tcp
            - ${https_port}:443/tcp
            # log_driver: ''
        command:
            - --web
            - --rancher
            - --rancher.domain=${domain}
            - --rancher.endpoint=${Endpoint}
            - --rancher.accesskey=${AccessKey}
            - --rancher.secretkey=${SecretKey}
            # parameter para loglevel?
            - --logLevel=DEBUG
            # config entrypoints
            - --defaultentrypoints=http,https
            - --entryPoints='Name:http Address::80'
            # - --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
            # - --entryPoints='Name:https Address::443 TLS compress'
            - --entryPoints='Name:https Address::443 TLS:/ssl/domain.crt,/ssl/domain.key'
            # acme config
            - --acme=${acme_enable}
            - --acme.entrypoint=https
            - --acme.email=${acme_email}
            - --acme.ondemand=${acme_ondemand}
            - --acme.onhostrule=${acme_onhostrule}
            - --acme.storage=/ssl/acme.json
        labels:
            io.rancher.scheduler.global: 'true'
        # tty: true
        # log_opt: {}
        # image: traefik:1.3.2
        # alpine nos permite conectarnos, el otro no
        image: traefik:1.3.2-alpine
        # environment:
        volumes:
            - traefik:/data
            - sslcerts:/ssl
            # - /opt/traefik/acme
            # - db_data:/var/lib/postgresql/data/pgdata
volumes:
    traefik:
        driver: rancher-nfs
        external: false
    sslcerts:
        driver: rancher-nfs
        external: false
# volumes:
#   sslcerts:
#     driver: local
#   traefik:
#     driver: local
