version: '2'
services:
    aeroo-docs:
        image: adhoc/aeroo-docs
        labels:
            # no need to have one on each host but better to distribute load
            # en realidad para repartir carga deberiamos agregar un lb si
            # llega a ser necesario
            # io.rancher.container.hostname_override: container_name
            # io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
            # lo desactivamos al global porque apartemente traia error aleatorio de generacion de pdf, tal vez haria falta un sticky o un lb arriba?
            # io.rancher.scheduler.global: 'true'
            io.rancher.container.pull_image: always
            # used to be autolinked on odoo containers
            # lo dejamos pero en realidad no nos está andando
            odoo_service: 'true'
